/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Vista;

import Modelo.Persona;

/**
 *
 * @author Usuario
 */
public class Interface extends javax.swing.JFrame {

    Termometro termometro;
    int temperatura;
    
    Persona p1 = new Persona("p1");
    Persona p2 = new Persona("p2");
    Persona p3 = new Persona("p3");
    Persona p4 = new Persona("p4");
    Persona p5 = new Persona("p5");

    /**
     * Creates new form Interface
     */
    public Interface() {
        
        initComponents();
        temperatura=50;
        termometro = new Termometro();
        termometro.setBounds(650, 40, 40, 250);
        desktopPane.add(termometro);
        termometro.setTemperature(50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        RButtonPers1 = new javax.swing.JRadioButton();
        RButtonPers2 = new javax.swing.JRadioButton();
        RButtonPers3 = new javax.swing.JRadioButton();
        RButtonPers4 = new javax.swing.JRadioButton();
        RButtonPers5 = new javax.swing.JRadioButton();
        MnsjPer1 = new javax.swing.JLabel();
        MnsjPer2 = new javax.swing.JLabel();
        MnsjPer3 = new javax.swing.JLabel();
        MnsjPer4 = new javax.swing.JLabel();
        MnsjPer5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RButtonPers1.setText("Suscrito");
        RButtonPers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonPers1ActionPerformed(evt);
            }
        });
        desktopPane.add(RButtonPers1);
        RButtonPers1.setBounds(160, 50, 98, 21);

        RButtonPers2.setText("Suscrito");
        RButtonPers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonPers2ActionPerformed(evt);
            }
        });
        desktopPane.add(RButtonPers2);
        RButtonPers2.setBounds(160, 110, 65, 21);

        RButtonPers3.setText("Suscrito");
        RButtonPers3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonPers3ActionPerformed(evt);
            }
        });
        desktopPane.add(RButtonPers3);
        RButtonPers3.setBounds(160, 160, 98, 21);

        RButtonPers4.setText("Suscrito");
        RButtonPers4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonPers4ActionPerformed(evt);
            }
        });
        desktopPane.add(RButtonPers4);
        RButtonPers4.setBounds(160, 210, 98, 21);

        RButtonPers5.setText("Suscrito");
        RButtonPers5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RButtonPers5ActionPerformed(evt);
            }
        });
        desktopPane.add(RButtonPers5);
        RButtonPers5.setBounds(160, 270, 98, 21);

        MnsjPer1.setText("Desuscrito");
        desktopPane.add(MnsjPer1);
        MnsjPer1.setBounds(350, 60, 180, 16);

        MnsjPer2.setText("Desuscrito");
        desktopPane.add(MnsjPer2);
        MnsjPer2.setBounds(350, 110, 180, 16);

        MnsjPer3.setText("Desuscrito");
        desktopPane.add(MnsjPer3);
        MnsjPer3.setBounds(350, 160, 190, 16);

        MnsjPer4.setText("Desuscrito");
        desktopPane.add(MnsjPer4);
        MnsjPer4.setBounds(350, 210, 200, 16);

        MnsjPer5.setText("Desuscrito");
        desktopPane.add(MnsjPer5);
        MnsjPer5.setBounds(350, 260, 210, 16);

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        desktopPane.add(jSlider1);
        jSlider1.setBounds(480, 280, 340, 70);

        jLabel1.setText("La temperatura actual es de :");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(520, 350, 160, 16);

        txtTemperatura.setEditable(false);
        txtTemperatura.setText("50");
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        desktopPane.add(txtTemperatura);
        txtTemperatura.setBounds(680, 350, 64, 22);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RButtonPers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonPers1ActionPerformed
        this.actualizarSuscribcionDeP1();
    }//GEN-LAST:event_RButtonPers1ActionPerformed

    private void RButtonPers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonPers2ActionPerformed
        // TODO add your handling code here:
        actualizarSuscribcionDeP2();
    }//GEN-LAST:event_RButtonPers2ActionPerformed

    private void RButtonPers3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonPers3ActionPerformed
        // TODO add your handling code here:
        actualizarSuscribcionDeP3();
    }//GEN-LAST:event_RButtonPers3ActionPerformed

    private void RButtonPers4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonPers4ActionPerformed
        // TODO add your handling code here:
        actualizarSuscribcionDeP4();
    }//GEN-LAST:event_RButtonPers4ActionPerformed

    private void RButtonPers5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RButtonPers5ActionPerformed
        // TODO add your handling code here:
        actualizarSuscribcionDeP5();
    }//GEN-LAST:event_RButtonPers5ActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        temperatura = jSlider1.getValue();
        txtTemperatura.setText(" " + temperatura);
        termometro.setTemperature(temperatura);
        actualizarSuscribcionDeP1();
        actualizarSuscribcionDeP2();
        actualizarSuscribcionDeP3();
        actualizarSuscribcionDeP4();
        actualizarSuscribcionDeP5();
        
    }//GEN-LAST:event_jSlider1StateChanged
    

    
    public void actualizarSuscribcionDeP1(){
        if (RButtonPers1.isSelected()==true) {
            MnsjPer1.setText(p1.actualizar(temperatura));
        }else if(RButtonPers1.isSelected()==false){
            MnsjPer1.setText("Desuscrito");
        }
    }
    public void actualizarSuscribcionDeP2(){
        if (RButtonPers2.isSelected()==true) {
            MnsjPer2.setText(p2.actualizar(temperatura));
        }else if(RButtonPers2.isSelected()==false){
            MnsjPer2.setText("Desuscrito");
        }
    }
    public void actualizarSuscribcionDeP3(){
        if (RButtonPers3.isSelected()==true) {
            MnsjPer3.setText(p3.actualizar(temperatura));
        }else if(RButtonPers3.isSelected()==false){
            MnsjPer3.setText("Desuscrito");
        }
    }
    public void actualizarSuscribcionDeP4(){
        if (RButtonPers4.isSelected()==true) {
            MnsjPer4.setText(p4.actualizar(temperatura));
        }else if(RButtonPers4.isSelected()==false){
            MnsjPer4.setText("Desuscrito");
        }
    }
    public void actualizarSuscribcionDeP5(){
        if (RButtonPers5.isSelected()==true) {
            MnsjPer5.setText(p5.actualizar(temperatura));
        }else if(RButtonPers5.isSelected()==false){
            MnsjPer5.setText("Desuscrito");
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MnsjPer1;
    private javax.swing.JLabel MnsjPer2;
    private javax.swing.JLabel MnsjPer3;
    private javax.swing.JLabel MnsjPer4;
    private javax.swing.JLabel MnsjPer5;
    private javax.swing.JRadioButton RButtonPers1;
    private javax.swing.JRadioButton RButtonPers2;
    private javax.swing.JRadioButton RButtonPers3;
    private javax.swing.JRadioButton RButtonPers4;
    private javax.swing.JRadioButton RButtonPers5;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables

}
